window.SoapyPanels = window.SoapyPanels || {};
window.SoapyPanels.i18nLocales = window.SoapyPanels.i18nLocales || {};

(function () {
  var english = window.SoapyPanels.i18nLocales.en || {};
  var strings = Object.assign({}, english.strings || {}, {
    "language.title": "Langue", "language.menu": "Langue : {language}", "language.description": "Choisissez la langue utilisée par l’interface de l’application.", "language.current": "Langue actuelle", "language.english": "English", "language.spanish": "Español", "language.optionsAria": "Options de langue",
    "menu.file": "Fichier", "menu.edit": "Édition", "menu.view": "Affichage", "menu.help": "Aide", "menu.newProject": "Nouveau projet", "menu.openProject": "Ouvrir un projet", "menu.saveProject": "Enregistrer le projet", "menu.saveProjectAs": "Enregistrer le projet sous…", "menu.loadImages": "Charger des images", "menu.undo": "Annuler", "menu.redo": "Rétablir", "menu.copy": "Copier", "menu.paste": "Coller", "menu.delete": "Supprimer",
    "topTools.addBubble": "Ajouter une bulle", "topTools.backgrounds": "Arrière-plans", "topTools.stickers": "Stickers", "topTools.styles": "Styles", "footer.color": "Couleur", "footer.pattern": "Dégradé", "footer.opacity": "Opacité", "footer.size": "Taille", "footer.zoom": "Zoom", "footer.lock": "Verrouillage", "stickers.canvas": "Stickers sur le canevas", "stickers.library": "Bibliothèque de stickers", "backgroundImages.heading": "Images d’arrière-plan", "backgroundImages.add": "Ajouter une image",
    "common.size": "Taille", "common.color": "Couleur", "common.opacity": "Opacité", "common.width": "Largeur", "common.height": "Hauteur", "common.rotation": "Rotation", "docker.text": "Texte", "docker.appearance": "Apparence", "docker.tail": "Queue", "docker.geometry": "Géométrie", "docker.font": "Police", "docker.targetWidth": "Largeur cible", "canvas.lock.unlockLabel": "Autoriser le déplacement des images", "stroke.solid": "Uni", "stroke.broken": "Contour en pointillés", "shape.extraTail": "Queue supplémentaire",
    "menu.chooseDockLayout": "Choisir la disposition du panneau…", "menu.chooseDockLayoutCurrent": "Disposition du panneau : {layout}…",
    "dockLayouts.title": "Choisir une disposition de panneau", "dockLayouts.description": "Choisissez l’organisation des onglets du panneau. Votre création reste inchangée.", "dockLayouts.optionsAria": "Dispositions de panneau disponibles", "dockLayouts.classic": "Disposition classique", "dockLayouts.modern": "Disposition moderne", "dockLayouts.classicDescription": "Conserver l’organisation actuelle sur deux lignes.", "dockLayouts.twoRow": "Disposition de panneau à deux lignes", "dockLayouts.twoRowDescription": "Conserver l’organisation actuelle sur deux lignes.", "dockLayouts.modernDescription": "Utiliser une seule ligne d’onglets défilante.", "dockLayouts.previous": "Faire défiler les onglets vers la gauche", "dockLayouts.next": "Faire défiler les onglets vers la droite", "dockLayouts.tabsAria": "Onglets du panneau", "dockStyles.title": "Style de panneau moderne", "dockStyles.optionsAria": "Styles de panneau moderne disponibles", "dockStyles.softCards": "Cartes douces", "dockStyles.softCardsDescription": "Des cartes arrondies et aérées avec des accents du thème.", "dockStyles.minimalUnderline": "Soulignement minimal", "dockStyles.minimalUnderlineDescription": "Une disposition spacieuse avec un simple soulignement actif.", "dockStyles.elevatedStudio": "Studio surélevé", "dockStyles.elevatedStudioDescription": "Des onglets flottants et des panneaux en relief avec des ombres plus profondes.", "dockStyles.compactPro": "Compact Pro", "dockStyles.compactProDescription": "Une disposition plus dense inspirée des outils créatifs professionnels.",
    "counts.images": { one: "{count} image", other: "{count} images" },
  });
  window.SoapyPanels.i18nLocales.fr = { label: "Français", lang: "fr", strings: strings, staticText: {}, staticAttributes: {} };
})();
