window.SoapyPanels = window.SoapyPanels || {};
window.SoapyPanels.i18nLocales = window.SoapyPanels.i18nLocales || {};

(function () {
  var english = window.SoapyPanels.i18nLocales.en || {};
  var strings = Object.assign({}, english.strings || {}, {
    "language.title": "Язык", "language.menu": "Язык: {language}", "language.description": "Выберите язык интерфейса приложения.", "language.current": "Текущий язык", "language.english": "English", "language.spanish": "Español", "language.optionsAria": "Настройки языка",
    "menu.file": "Файл", "menu.edit": "Правка", "menu.view": "Вид", "menu.help": "Справка", "menu.newProject": "Новый проект", "menu.openProject": "Открыть проект", "menu.saveProject": "Сохранить проект", "menu.saveProjectAs": "Сохранить проект как…", "menu.loadImages": "Загрузить изображения", "menu.undo": "Отменить", "menu.redo": "Повторить", "menu.copy": "Копировать", "menu.paste": "Вставить", "menu.delete": "Удалить",
    "topTools.addBubble": "Добавить облачко", "topTools.backgrounds": "Фоны", "topTools.stickers": "Стикеры", "topTools.styles": "Стили", "footer.color": "Цвет", "footer.pattern": "Градиент", "footer.opacity": "Непрозрачность", "footer.size": "Размер", "footer.zoom": "Масштаб", "footer.lock": "Блокировка", "stickers.canvas": "Стикеры на холсте", "stickers.library": "Библиотека стикеров", "backgroundImages.heading": "Фоновые изображения", "backgroundImages.add": "Добавить изображение",
    "common.size": "Размер", "common.color": "Цвет", "common.opacity": "Непрозрачность", "common.width": "Ширина", "common.height": "Высота", "common.rotation": "Поворот", "docker.text": "Текст", "docker.appearance": "Внешний вид", "docker.tail": "Хвост", "docker.geometry": "Геометрия", "docker.font": "Шрифт", "docker.targetWidth": "Целевая ширина", "canvas.lock.unlockLabel": "Разрешить перемещение изображений", "stroke.solid": "Сплошной", "stroke.broken": "Пунктирный контур", "shape.extraTail": "Дополнительный хвост",
    "menu.chooseDockLayout": "Выбрать компоновку панели…", "menu.chooseDockLayoutCurrent": "Компоновка панели: {layout}…",
    "dockLayouts.title": "Выбор компоновки панели", "dockLayouts.description": "Выберите расположение вкладок панели. Ваш рисунок останется без изменений.", "dockLayouts.optionsAria": "Доступные компоновки панели", "dockLayouts.classic": "Классическая компоновка", "dockLayouts.modern": "Современная компоновка", "dockLayouts.classicDescription": "Сохранить существующее расположение в две строки.", "dockLayouts.twoRow": "Двухрядная компоновка панели", "dockLayouts.twoRowDescription": "Сохранить существующее расположение в две строки.", "dockLayouts.modernDescription": "Использовать одну компактную строку с прокруткой.", "dockLayouts.previous": "Прокрутить вкладки панели влево", "dockLayouts.next": "Прокрутить вкладки панели вправо", "dockLayouts.tabsAria": "Вкладки панели", "dockStyles.title": "Стиль современной панели", "dockStyles.optionsAria": "Доступные стили современной панели", "dockStyles.softCards": "Мягкие карточки", "dockStyles.softCardsDescription": "Воздушные закруглённые карточки с акцентами темы.", "dockStyles.minimalUnderline": "Минимальное подчёркивание", "dockStyles.minimalUnderlineDescription": "Просторная компоновка с простой активной линией.", "dockStyles.elevatedStudio": "Объёмная студия", "dockStyles.elevatedStudioDescription": "Плавающие вкладки и приподнятые панели с более глубокими тенями.", "dockStyles.compactPro": "Компактный Pro", "dockStyles.compactProDescription": "Более плотная компоновка в стиле профессиональных творческих инструментов.",
    "counts.images": { one: "{count} изображение", few: "{count} изображения", many: "{count} изображений", other: "{count} изображения" },
  });
  window.SoapyPanels.i18nLocales.ru = { label: "Русский", lang: "ru", strings: strings, staticText: {}, staticAttributes: {} };
})();
